import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Minus, Square, Copy as RestoreIcon, ArrowDown, ArrowRight, ArrowUp, Check, CheckCheck, ChevronDown, ChevronRight, CircleHelp, Code2, Copy, File, FileCheck2, FileImage, FilePlus2, FileSpreadsheet, FileText, Files, Folder, FolderOpen, LayoutDashboard, LoaderCircle, Monitor, MoreHorizontal, Pause, Pencil, Play, Plus, RefreshCw, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Terminal, Trash2, Upload, X} from 'lucide-react';
import './styles.css';
import {JA,TW} from './locales';

const DEFAULT={engine:'auto',lang:'zh_cn',matrix_motion:true,out_mode:'original',output_dir:'',naming_tpl:'{name}',auto_open:false,open_folder:false,clear_after:false,compress_pdf:false,wm1_text:'',wm1_pos:'None',wm2_text:'',wm2_pos:'None',wm_font:'',wm_size:60,wm_color:'#C0C0C0',wm_alpha:.3,pg_enabled:false,pg_pos:'bc',pg_format:'- {n} / {total} -',merge_all:false,split_word_page:false,split_ppt_page:false,split_pdf_page:false,split_excel_sheet:false,split_excel_page:false,password:'',excel_fit:false,excel_fit_tall:false,clear_metadata:false};
const EMPTY={files:[],busy:false,progress:0,maximum:1,label:'',logs:[],last_output:'',actual_engine:'',presets:[],fonts:[],translations:{},positions:[]};
const LABELS={workspace:['转换工作台','Workspace'],activity:['运行记录','Activity'],preferences:['偏好设置','Preferences'],subtitle:['让每一份文档，有序抵达。','A clearer path from document to PDF.'],queue:['转换队列','Conversion queue'],add:['添加文件','Add files'],folder:['添加文件夹','Add folder'],empty:['文件就位，即刻开始','Your next PDF starts here'],drop:['拖放文件至此，或从电脑中选择','Drop files here, or select them from your computer'],browse:['选择文件','Choose files'],local:['所有文件仅在本机处理','Your files stay on this device'],settings:['转换设置','Conversion settings'],general:['常用','General'],watermark:['水印','Watermark'],advanced:['高级','Advanced'],output:['输出位置','Output location'],original:['与源文件相同','Source folder'],custom:['自定义目录','Custom folder'],naming:['文件命名','File naming'],organize:['输出方式','Output mode'],individual:['逐个转换','Individual'],merge:['合并为一个 PDF','Merge into one PDF'],split:['拆分设置','Split options'],preview:['预览效果','Preview PDF'],start:['开始转换','Convert to PDF'],cancel:['取消任务','Cancel'],ready:['准备就绪','Ready to convert'],files:['个文件','files'],pending:['待处理','Queued'],running:['转换中','Converting'],finishing:['生成输出','Finalizing'],success:['已完成','Completed'],failed:['转换失败','Failed'],partial:['部分失败','Partial'],cancelled:['已取消','Cancelled'],skipped:['已跳过','Skipped'],all:['全部文件','All files'],name:['文件','File'],status:['状态','Status'],range:['页码 / 工作表','Pages / sheets'],allpages:['全部','All'],retry:['重试失败项','Retry failed'],open:['打开输出目录','Open output'],errors:['仅看错误','Errors only'],copy:['复制日志','Copy log'],motion:['动态代码雨','Code rain'],motiondesc:['用低亮度字符流点亮工作台。','A subtle stream of code, at your pace.'],language:['界面语言','Language'],presets:['我的预设','My presets'],savepreset:['保存当前配置','Save current settings'],presetname:['预设名称','Preset name'],save:['保存','Save'],close:['关闭','Close'],engine:['转换引擎','Conversion engine'],auto:['自动选择 · 优先 Office','Auto · Office first'],notrun:['运行后显示实际使用的引擎','Actual engine appears when conversion starts'],offline:['离线处理','Offline processing'],selected:['已选择','Selected'],clear:['清空队列','Clear queue'],rangehelp:['输入页码，如 1-3,5,8-；留空表示全部。','Pages, e.g. 1-3,5,8-. Leave empty for all.'],noname:['请输入名称','Enter a name'],logsEmpty:['转换记录将显示在这里','Your conversion activity will appear here'],webpreview:['界面预览 · 转换请使用桌面版','UI preview · Use the desktop app to convert'],busy:['正在处理，请稍候','Processing your documents'],overwrite:['同名文件自动保留副本','Existing files are kept; new copies are numbered'],safe:['本地转换，不上传文件','Local conversion. No file uploads.'],taghint:['可用标签：{name} 文件名 · {seq} 序号 · {sheet} 工作表 · {pseq} 页码','Tags: {name} filename · {seq} sequence · {sheet} sheet · {pseq} page'],load:['应用','Apply'],delete:['删除','Delete'],noPreset:['还没有预设，保存一套常用配置吧。','Save your frequently used settings as a preset.'],after:['转换完成后','After conversion'],protection:['文档保护','Document protection'],look:['外观与体验','Appearance'],font:['字体','Font'],text:['水印文字','Watermark text'],position:['位置','Position'],size:['字号','Size'],opacity:['不透明度','Opacity'],color:['颜色','Color'],pages:['页码','Page numbers']};
const splitKeys=['split_word_page','split_ppt_page','split_pdf_page','split_excel_sheet','split_excel_page'];
const formats={Word:{label:'DOC',class:'word',Icon:FileText},Excel:{label:'XLS',class:'excel',Icon:FileSpreadsheet},PowerPoint:{label:'PPT',class:'ppt',Icon:File},PDF:{label:'PDF',class:'pdf',Icon:FileText},Image:{label:'IMG',class:'image',Icon:FileImage}};
const bytes=n=>n>=1048576?(n/1048576).toFixed(1)+' MB':Math.max(1,Math.round(n/1024))+' KB';

function Rain({enabled}){
 const ref=useRef(null);
 useEffect(()=>{const canvas=ref.current,ctx=canvas.getContext('2d');let timer;let columns=[];let last=0;
  const animate=enabled&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const resize=()=>{canvas.width=canvas.clientWidth;canvas.height=canvas.clientHeight;columns=Array.from({length:Math.ceil(canvas.width/18)},()=>Math.random()*canvas.height);draw(true)};
  function draw(still=false){const w=canvas.width,h=canvas.height;ctx.fillStyle='rgba(13,22,17,.12)';ctx.fillRect(0,0,w,h);ctx.font='11px Consolas,monospace';columns.forEach((y,i)=>{ctx.fillStyle=i%4===0?'#427751':'#25402e';ctx.fillText('01{}[]<>/ABCDEF'[Math.floor(Math.random()*14)],i*18,y);if(!still)columns[i]=(y>h+50&&Math.random()>.95)?-20:y+12})}
  const tick=now=>{if(animate&&!document.hidden&&now-last>90){draw();last=now}timer=requestAnimationFrame(tick)};
  const observer=new ResizeObserver(resize);observer.observe(canvas);if(animate)timer=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(timer);observer.disconnect()};
 },[enabled]);return <canvas ref={ref} className="code-rain" aria-hidden="true"/>;
}
function Toggle({checked,onChange,label,disabled=false}){return <button type="button" className={'toggle '+(checked?'on':'')} role="switch" aria-checked={!!checked} aria-label={label} disabled={disabled} onClick={()=>onChange(!checked)}><span/></button>}
function Field({label,children,hint}){return <label className="field"><span className="field-label">{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function App(){
 const [data,setData]=useState(EMPTY),[cfg,setCfg]=useState(DEFAULT),[connected,setConnected]=useState(false),[section,setSection]=useState('workspace'),[tab,setTab]=useState('general'),[selected,setSelected]=useState([]),[filter,setFilter]=useState('all'),[showLog,setShowLog]=useState(false),[errors,setErrors]=useState(false),[toast,setToast]=useState(''),[dialog,setDialog]=useState(null),[rangeValue,setRangeValue]=useState(''),[sheetNames,setSheetNames]=useState([]),[sheetLoading,setSheetLoading]=useState(false),[presetName,setPresetName]=useState(''),[drag,setDrag]=useState(false),[saving,setSaving]=useState(false),[maximized,setMaximized]=useState(false);
 const configRef=useRef(cfg);configRef.current=cfg;const initialized=useRef(false);const dirty=useRef(false);
 const t=k=>(cfg.lang==='ja'?JA[k]:cfg.lang==='zh_tw'?TW[k]:null)||(LABELS[k]||[k,k])[cfg.lang==='en'?1:0];
 const old=(key,fallback)=>data.translations[key]||fallback||key;
 const notify=message=>setToast(String(message?.message||message));
 async function api(method,...args){if(!window.pywebview?.api){notify(t('webpreview'));return null}try{return await window.pywebview.api[method](...args)}catch(error){notify(error);return null}}
 const update=(key,value)=>{dirty.current=true;setCfg(current=>({...current,[key]:value}))};
 const applyData=snapshot=>{if(snapshot){setData(snapshot);setSelected(current=>current.filter(p=>snapshot.files.some(f=>f.path===p)))}};
 useEffect(()=>{let active=true,timer,started=false;const connect=async()=>{if(!window.pywebview?.api)return;try{const result=await window.pywebview.api.snapshot();if(!active)return;applyData(result);if(!initialized.current){setCfg(result.config);initialized.current=true}setConnected(true)}catch(error){if(active)notify(error)}if(active)timer=setTimeout(connect,450)};const boot=()=>{if(!started&&window.pywebview?.api){started=true;connect()}};boot();window.addEventListener('pywebviewready',boot);return()=>{active=false;clearTimeout(timer);window.removeEventListener('pywebviewready',boot)}},[]);
 useEffect(()=>{if(!initialized.current||!dirty.current)return;const timer=setTimeout(async()=>{await api('save_config',cfg);dirty.current=false},500);return()=>clearTimeout(timer)},[cfg]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timer)},[toast]);
 useEffect(()=>{const key=e=>{if(e.ctrlKey&&e.key.toLowerCase()==='o'){e.preventDefault();if(!data.busy)api('pick_files').then(applyData)}if(e.key==='Escape')setDialog(null)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[data.busy]);
 const choose=async()=>applyData(await api('pick_files'));
 const queue=async(op,paths=selected)=>{applyData(await api('modify_queue',op,paths));if(op==='remove'||op==='clear')setSelected([])};
 const start=async(retry=false)=>{await api('start',configRef.current,retry);const current=await api('snapshot');applyData(current)};
 const toggleSelect=path=>setSelected(s=>s.includes(path)?s.filter(p=>p!==path):[...s,path]);
 const counts={pending:data.files.filter(f=>f.status==='pending').length,success:data.files.filter(f=>f.status==='success').length,failed:data.files.filter(f=>['failed','partial'].includes(f.status)).length};
 const rows=data.files.filter(f=>filter==='all'||(filter==='failed'?['failed','partial'].includes(f.status):f.status===filter));
 async function editRange(file){setDialog(file);setRangeValue(file.range);setSheetNames([]);if(file.type==='Excel'){setSheetLoading(true);setSheetNames(await api('sheets',file.path)||[]);setSheetLoading(false)}}
 const setMode=mode=>{dirty.current=true;setCfg(c=>({...c,merge_all:mode==='merge',...(mode==='merge'?Object.fromEntries(splitKeys.map(k=>[k,false])):{})}))};
 const switchSetting=(key,value)=>{dirty.current=true;setCfg(c=>({...c,[key]:value,...(splitKeys.includes(key)&&value?{merge_all:false}:{}),...(key==='split_excel_sheet'&&value?{split_excel_page:false}:{}),...(key==='split_excel_page'&&value?{split_excel_sheet:false}:{})}))};
 const progress=Math.min(100,Math.round(100*data.progress/Math.max(1,data.maximum)));
 const statusIcon=status=>status==='success'?<Check size={13}/>:['running','finishing'].includes(status)?<LoaderCircle size={13} className="spin"/>:['failed','partial'].includes(status)?<X size={13}/>:<span className="status-dot"/>;
 const visibleLogs=data.logs.filter(l=>!errors||l.error);
 const settingsChecks=(items)=>items.map(([key,label])=><div className="setting-row" key={key}><span>{label}</span><Toggle checked={cfg[key]} onChange={v=>switchSetting(key,v)} label={label} disabled={data.busy}/></div>);
 return <div className="app-shell" onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget))setDrag(false)}} onDrop={e=>{e.preventDefault();setDrag(false)}}>
  <aside className="rail"><div className="brand-symbol" title="矩流 PDF · MatrixFlow PDF"><img src={`${import.meta.env.BASE_URL}app-icon.png`} alt="MatrixFlow PDF" draggable="false"/></div><div className="rail-divider"/>{[['workspace',LayoutDashboard],['activity',Terminal],['preferences',SlidersHorizontal]].map(([key,Icon])=><button key={key} title={t(key)} aria-label={t(key)} className={'rail-button '+(section===key?'active':'')} onClick={()=>setSection(key)}><Icon size={21}/></button>)}<div className="rail-bottom"><ShieldCheck size={19}/><span>LOCAL</span></div></aside>
  <div className="main-shell">
   <header className="topbar pywebview-drag-region" onDoubleClick={e=>{if(!e.target.closest('button'))api('window_control','maximize').then(v=>v!==null&&setMaximized(v))}}><div className="wordmark pywebview-drag-region">Matrix<span className="pywebview-drag-region">Flow</span> <span className="brand-format pywebview-drag-region">PDF</span><span className="edition pywebview-drag-region">矩流</span></div><div className="window-controls"><button aria-label="最小化" title="最小化" disabled={!connected} onClick={()=>api('window_control','minimize')}><Minus size={15}/></button><button aria-label={maximized?'还原':'最大化'} title={maximized?'还原':'最大化'} disabled={!connected} onClick={()=>api('window_control','maximize').then(v=>v!==null&&setMaximized(v))}>{maximized?<RestoreIcon size={13}/>:<Square size={13}/>}</button><button className="window-close" aria-label="关闭窗口" title="关闭窗口" disabled={!connected} onClick={()=>api('window_control','close')}><X size={16}/></button></div></header>
   <main className="page-scroll">
    <div className="page-heading"><div><div className="eyebrow">YOUR DOCUMENTS. YOUR CONTROL.</div><h1>{t(section)}</h1><p>{t('subtitle')}</p></div><div className="system-art"><Rain enabled={cfg.matrix_motion}/><div className="system-code"><span>LOCAL / DOCUMENT ENGINE</span><strong><span className="terminal-prompt">&gt;_</span> make it <em>pdf.</em></strong><small>DOC · XLS · PPT → PDF</small></div></div></div>
    {section==='workspace'&&<>
     <div className="workspace-grid">
      <section className={'queue-card card '+(drag?'dragging':'')}>
       <div className="card-header"><div><h2>{t('queue')} <span className="count-badge">{String(data.files.length).padStart(2,'0')}</span></h2><span className="subtle">DOC / XLS / PPT / PDF / IMG</span></div><div className="queue-actions"><button className="button secondary" onClick={()=>api('pick_folder',true).then(applyData)} disabled={data.busy} title={t('folder')}><Folder size={16}/><span className="folder-label">{t('folder')}</span></button><button className="button primary small" disabled={data.busy} onClick={choose}><Plus size={16}/>{t('add')}</button></div></div>
       <div className="queue-filters"><div className="filter-tabs">{['all','pending','success','failed'].map(key=><button key={key} className={filter===key?'current':''} onClick={()=>setFilter(key)}>{t(key)}{key!=='all'&&<span>{counts[key]}</span>}</button>)}</div><button className="icon-button" disabled={data.busy||!data.files.length} onClick={()=>queue('clear',[])} title={t('clear')} aria-label={t('clear')}><Trash2 size={15}/></button></div>
       {!data.files.length?<div className="empty-state"><div className="upload-art"><span className="orbit one"/><span className="orbit two"/><div className="ghost-file left"><FileSpreadsheet size={24}/></div><div className="ghost-file right"><FileImage size={24}/></div><div className="main-file"><FilePlus2 size={39} strokeWidth={1.3}/><span>PDF</span></div><div className="upload-dot"><ArrowUp size={16}/></div></div><h3>{t('empty')}</h3><p>{t('drop')}</p><button className="button secondary" disabled={data.busy} onClick={choose}><Upload size={16}/>{t('browse')}<kbd>Ctrl O</kbd></button><div className="private-note"><ShieldCheck size={13}/>{t('local')}</div></div>:<div className="file-table-wrap"><table className="file-table"><thead><tr><th className="check-cell"><input type="checkbox" aria-label={t('all')} checked={rows.length>0&&rows.every(f=>selected.includes(f.path))} onChange={e=>setSelected(e.target.checked?rows.map(f=>f.path):[])}/></th><th>{t('name')}</th><th>{t('range')}</th><th>{t('status')}</th><th/></tr></thead><tbody>{rows.map(file=>{const fmt=formats[file.type]||formats.PDF;return <tr key={file.path} className={selected.includes(file.path)?'selected':''}><td><input type="checkbox" aria-label={file.name} checked={selected.includes(file.path)} onChange={()=>toggleSelect(file.path)}/></td><td><div className="file-name-cell"><div className={'file-icon '+fmt.class}><fmt.Icon size={22}/><small>{fmt.label}</small></div><div className="filename"><strong title={file.path}>{file.name}</strong><small title={file.output}>{bytes(file.size)}<span>→</span>{file.output}</small></div></div></td><td><button className="range-button" disabled={data.busy} onClick={()=>editRange(file)} title={file.range||t('allpages')}>{file.range||t('allpages')}<Pencil size={11}/></button></td><td><span className={'status '+file.status}>{statusIcon(file.status)}{t(file.status)}</span></td><td><button className="icon-button remove" disabled={data.busy} aria-label={t('delete')+' '+file.name} onClick={()=>queue('remove',[file.path])}><X size={14}/></button></td></tr>})}</tbody></table>{!rows.length&&<div className="no-results">{t('all')} · 0</div>}</div>}
       <div className="queue-bottom"><span><Files size={14}/>{selected.length?t('selected')+' '+selected.length:data.files.length+' '+t('files')}</span><div><button className="icon-button" disabled={data.busy||selected.length!==1} title="↑" aria-label="Move up" onClick={()=>queue('up')}><ArrowUp size={15}/></button><button className="icon-button" disabled={data.busy||selected.length!==1} title="↓" aria-label="Move down" onClick={()=>queue('down')}><ArrowDown size={15}/></button><button className="icon-button" disabled={data.busy||!selected.length} title={t('delete')} aria-label={t('delete')} onClick={()=>queue('remove')}><Trash2 size={15}/></button></div></div>
      </section>
      <section className="settings-card card"><div className="card-header"><h2><Settings2 size={17}/>{t('settings')}</h2><span className="micro-label">CONFIG</span></div><div className="setting-tabs" role="tablist">{['general','watermark','advanced'].map(key=><button role="tab" aria-selected={tab===key} key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{t(key)}</button>)}</div>
       <div className="settings-body"><fieldset disabled={data.busy}>
        {tab==='general'&&<><Field label={t('engine')}><select value={cfg.engine} onChange={e=>update('engine',e.target.value)}><option value="auto">{t('auto')}</option><option value="office">Microsoft Office</option><option value="wps">WPS Office</option></select></Field><div className="engine-info"><span className="tiny-led"/>{data.actual_engine||t('notrun')}</div><div className="section-rule"/><Field label={t('output')}><div className="segmented">{['original','custom'].map(mode=><button key={mode} className={cfg.out_mode===mode?'active':''} onClick={()=>update('out_mode',mode)}>{t(mode)}</button>)}</div></Field>{cfg.out_mode==='custom'&&<div className="path-input"><input value={cfg.output_dir} onChange={e=>update('output_dir',e.target.value)} aria-label={t('output')} placeholder="C:\\Documents\\PDF"/><button className="icon-button" aria-label={t('folder')} onClick={async()=>{const p=await api('pick_folder',false);if(p)update('output_dir',p)}}><FolderOpen size={16}/></button></div>}<Field label={t('naming')} hint={t('overwrite')}><div className="input-with-icon"><Code2 size={14}/><input className="mono" value={cfg.naming_tpl} onChange={e=>update('naming_tpl',e.target.value)}/><span className="input-suffix">.pdf</span></div></Field><details className="tag-help"><summary><CircleHelp size={12}/>{cfg.lang==='en'?'Naming tags':'命名标签'}<ChevronDown size={12}/></summary><p>{t('taghint')}</p></details><div className="section-rule"/><Field label={t('organize')}><div className="mode-options"><button className={!cfg.merge_all?'chosen':''} onClick={()=>setMode('individual')}><Files size={19}/><span>{t('individual')}</span><i>{!cfg.merge_all&&<Check size={10}/>}</i></button><button className={cfg.merge_all?'chosen':''} onClick={()=>setMode('merge')}><FileCheck2 size={19}/><span>{t('merge')}</span><i>{cfg.merge_all&&<Check size={10}/>}</i></button></div></Field><details className="split-details" open={splitKeys.some(k=>cfg[k])||undefined}><summary>{t('split')}<ChevronDown size={14}/></summary>{settingsChecks([['split_word_page','Word · '+old('chk_split_page')],['split_ppt_page','PowerPoint · '+old('chk_split_page')],['split_pdf_page','PDF · '+old('chk_split_page')],['split_excel_sheet','Excel · '+old('chk_by_sheet')],['split_excel_page','Excel · '+old('chk_split_page')]])}</details></>}
        {tab==='watermark'&&<><Field label={t('font')}><select value={cfg.wm_font} onChange={e=>update('wm_font',e.target.value)}><option value="">{cfg.lang==='en'?'System font':'系统字体'}</option>{data.fonts.map(f=><option key={f}>{f}</option>)}</select></Field>{[1,2].map(n=><div className="watermark-block" key={n}><Field label={t('text')+' 0'+n}><input value={cfg['wm'+n+'_text']} onChange={e=>update('wm'+n+'_text',e.target.value)} placeholder={n===1?'CONFIDENTIAL':'{date:yyyy-mm-dd}'}/></Field><Field label={t('position')}><select value={cfg['wm'+n+'_pos']} onChange={e=>update('wm'+n+'_pos',e.target.value)}>{(data.positions.length?data.positions:[['None','pos_none'],['diag','pos_diag_center'],['bc','pos_bottom_center']]).map(([id,key])=><option key={id} value={id}>{old(key,id)}</option>)}</select></Field></div>)}<div className="two-fields"><Field label={t('size')}><input type="number" min="10" max="300" value={cfg.wm_size} onChange={e=>update('wm_size',Number(e.target.value))}/></Field><Field label={t('color')}><input type="color" value={cfg.wm_color} onChange={e=>update('wm_color',e.target.value)}/></Field></div><Field label={t('opacity')+' · '+Math.round(cfg.wm_alpha*100)+'%'}><input type="range" min="0" max="1" step=".05" value={cfg.wm_alpha} onChange={e=>update('wm_alpha',Number(e.target.value))}/></Field>{settingsChecks([['pg_enabled',t('pages')]])}{cfg.pg_enabled&&<><input value={cfg.pg_format} aria-label={t('pages')} onChange={e=>update('pg_format',e.target.value)}/><select value={cfg.pg_pos} aria-label={t('position')} onChange={e=>update('pg_pos',e.target.value)}><option value="bc">{old('pg_pos_bc')}</option><option value="br">{old('pg_pos_br')}</option></select></>}<button className="button secondary full" disabled={!data.files.length} onClick={()=>api('preview',selected[0]||data.files[0].path,cfg)}><Monitor size={16}/>{t('preview')}</button></>}
        {tab==='advanced'&&<><h3 className="settings-subtitle">Excel</h3>{settingsChecks([['excel_fit',old('chk_fit_width')],['excel_fit_tall',old('chk_fit_height')]])}<div className="section-rule"/><h3 className="settings-subtitle">{t('protection')}</h3><Field label={old('lbl_password','PDF 密码')}><input type="password" value={cfg.password} onChange={e=>update('password',e.target.value)} autoComplete="off" placeholder="••••••••"/></Field>{settingsChecks([['clear_metadata',old('chk_meta_clear')],['compress_pdf',old('chk_compress')]])}<div className="section-rule"/><h3 className="settings-subtitle">{t('after')}</h3>{settingsChecks([['auto_open',old('chk_open_done')],['open_folder',old('chk_open_folder')],['clear_after',old('chk_clear_after')]])}</>}
       </fieldset></div><button className="preset-shortcut" onClick={()=>setDialog('preset')} disabled={data.busy}><SlidersHorizontal size={15}/>{t('savepreset')}<Plus size={14}/></button></section>
     </div>
     <div className="workspace-note"><ShieldCheck size={14}/><span>{t('safe')}</span><span className="note-right">MATRIXFLOW PDF / V6.0</span></div>
    </>}
    {section==='activity'&&<section className="card activity-card"><div className="card-header"><h2><Terminal size={19}/>{t('activity')}</h2><div className="queue-actions"><button className="button secondary" onClick={()=>{navigator.clipboard.writeText(visibleLogs.map(l=>`${l.time} ${l.message}`).join('\n')).then(()=>notify(t('copy')+' ✓')).catch(notify)}}><Copy size={14}/>{t('copy')}</button><button className={'button '+(errors?'selected-button':'secondary')} onClick={()=>setErrors(!errors)}>{t('errors')}</button></div></div><div className="activity-list">{visibleLogs.length?visibleLogs.map((l,i)=><div key={i} className={'log-line '+(l.error?'error':'')}><time>{l.time}</time><span className="log-indicator">{l.error?'ERR':'SYS'}</span><span>{l.message}</span></div>):<div className="no-activity"><Terminal size={34}/><p>{t('logsEmpty')}</p></div>}</div></section>}
    {section==='preferences'&&<div className="preferences-grid"><section className="card preference-card"><h2><Sparkles size={19}/>{t('look')}</h2><div className="setting-row"><div><strong>{t('motion')}</strong><p>{t('motiondesc')}</p></div><Toggle checked={cfg.matrix_motion} onChange={v=>update('matrix_motion',v)} label={t('motion')}/></div><Field label={t('language')}><select value={cfg.lang} onChange={e=>update('lang',e.target.value)}><option value="zh_cn">简体中文</option><option value="zh_tw">繁體中文</option><option value="en">English</option><option value="ja">日本語</option></select></Field><div className="theme-preview"><Rain enabled={cfg.matrix_motion}/><span><Code2 size={24}/> Matrix <small>CHARCOAL / TERMINAL GREEN</small></span></div></section><section className="card preference-card"><h2><SlidersHorizontal size={19}/>{t('presets')}</h2>{data.presets.length?data.presets.map(name=><div className="preset-item" key={name}><span>{name}</span><button className="button secondary small" disabled={data.busy} onClick={async()=>{const s=await api('preset','load',name);if(s){dirty.current=false;setCfg(s.config);applyData(s)}}}>{t('load')}</button><button className="icon-button" disabled={data.busy} aria-label={t('delete')+' '+name} onClick={()=>api('preset','delete',name).then(applyData)}><Trash2 size={14}/></button></div>):<p className="muted-text">{t('noPreset')}</p>}<button className="button secondary full" onClick={()=>setDialog('preset')} disabled={data.busy}><Plus size={16}/>{t('savepreset')}</button></section></div>}
   </main>
   {showLog&&<div className="log-drawer"><div><strong><Terminal size={14}/>{t('activity')}</strong><button className="icon-button" onClick={()=>setShowLog(false)} aria-label={t('close')}><X size={15}/></button></div><div className="mini-log">{data.logs.slice(-30).map((l,i)=><p className={l.error?'error':''} key={i}><time>{l.time}</time>{l.message}</p>)}{!data.logs.length&&<p>{t('logsEmpty')}</p>}</div></div>}
   <footer className="runbar"><div className="runbar-progress" style={{width:progress+'%'}}/><div className="run-summary"><div className={'ready-dot '+(data.busy?'processing':'')}>{data.busy?<LoaderCircle size={19} className="spin"/>:<Check size={18}/>}</div><div><strong>{data.busy?(data.label||t('busy')):data.label||t('ready')}</strong><span>{data.files.length} {t('files')}<b>·</b>{cfg.merge_all?t('merge'):t('individual')}{data.busy&&' · '+progress+'%'}</span></div></div><div className="run-actions"><button className={'icon-button log-toggle '+(showLog?'active':'')} onClick={()=>setShowLog(!showLog)} aria-label={t('activity')} title={t('activity')}><Terminal size={18}/>{data.logs.some(l=>l.error)&&<i/>}</button>{data.last_output&&!data.busy&&<button className="button secondary output-button" onClick={()=>api('open_output')} title={t('open')}><FolderOpen size={17}/></button>}{counts.failed>0&&!data.busy&&<button className="button secondary retry-button" onClick={()=>start(true)} title={t('retry')}><RefreshCw size={16}/><span>{t('retry')}</span></button>}{data.busy?<button className="button cancel-button" onClick={()=>api('cancel')}><Pause size={15}/>{t('cancel')}</button>:<button className="button primary convert-button" disabled={!connected||!data.files.length||saving} onClick={()=>start()}><Play size={15} fill="currentColor"/>{t('start')}<ArrowRight size={17}/></button>}</div></footer>
  </div>
  {drag&&<div className="drop-overlay"><Upload size={40}/><h2>{t('drop')}</h2></div>}
  {toast&&<div className="toast" role="status"><CircleHelp size={17}/><span>{toast}</span><button className="icon-button" onClick={()=>setToast('')} aria-label={t('close')}><X size={15}/></button></div>}
  {dialog&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDialog(null)}}><section role="dialog" aria-modal="true" aria-labelledby="dialog-title" className="modal"><div className="modal-head"><h2 id="dialog-title">{dialog==='preset'?t('savepreset'):t('range')}</h2><button className="icon-button" onClick={()=>setDialog(null)} aria-label={t('close')}><X size={18}/></button></div>{dialog==='preset'?<Field label={t('presetname')}><input autoFocus value={presetName} onChange={e=>setPresetName(e.target.value)} placeholder={cfg.lang==='en'?'e.g. Weekly reports':'例如：每周报表'}/></Field>:<><p className="modal-filename">{dialog.name}</p>{dialog.type==='Excel'?sheetLoading?<p><LoaderCircle className="spin" size={17}/> {t('busy')}</p>:<div className="sheet-options">{sheetNames.map(name=><label key={name}><input type="checkbox" checked={rangeValue.split(',').includes(name)} onChange={e=>setRangeValue(e.target.checked?[...rangeValue.split(',').filter(Boolean),name].join(','):rangeValue.split(',').filter(n=>n!==name).join(','))}/>{name}</label>)}{!sheetNames.length&&<p>{cfg.lang==='en'?'No sheets found. See the activity log.':'未读取到工作表，请查看运行记录。'}</p>}</div>:<Field label={t('range')} hint={t('rangehelp')}><input autoFocus value={rangeValue} onChange={e=>setRangeValue(e.target.value)} placeholder="1-3,5,8-"/></Field>}</>}<div className="modal-actions"><button className="button secondary" onClick={()=>setDialog(null)}>{t('close')}</button><button className="button primary" disabled={sheetLoading||saving} onClick={async()=>{setSaving(true);try{if(dialog==='preset'){if(!presetName.trim()){notify(t('noname'));return}const s=await api('preset','save',presetName,cfg);if(s){applyData(s);setDialog(null);setPresetName('')}}else{const s=await api('set_range',dialog.path,rangeValue);if(s){applyData(s);setDialog(null)}}}finally{setSaving(false)}}}><Check size={16}/>{t('save')}</button></div></section></div>}
 </div>;
}
const mount=document.getElementById('root');
if(mount)createRoot(mount).render(<App/>);
